image:
  containerName: admin-service
  name: titovegor/titov-service
  tag: latest

configs:
  NODE_ENV: production
  FLUENT_HOST: host.minikube.internal

service:
  ports:
    - name: http
      port: 80
      containerPort: 8082

ingress:
  - path: /api/titov-service
    port: http