{{- define "common.ingress" -}}

{{- $common := dict "Values" .Values.common -}} # Values з common Chart
{{- $noCommon := omit .Values "common" -}} # Values з основного Chart
{{- $overrides := dict "Values" $noCommon -}} # записуємо common Values в змінну Values
{{- $noValues := omit . "Values" -}} # містить усе крім Values, зокрема Chart, Release
{{- with merge $noValues $overrides $common -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
        {{- range $ingress := .Values.ingress }}
          - path: {{ $ingress.path }}
            pathType: "Prefix"
            backend:
              service:
                name: {{ include "common.fullname" $ }}
                port:
                  name: {{ $ingress.port }}
        {{- end }}
{{- end -}}
{{- end -}}