image:
  containerName: movie-service
  name: jedich/movie-test
  tag: latest

configs:
  USER_SERVICE_NAME: "local-user-service"
  ADMIN_SERVICE_NAME: "local-admin-service"
  KAFKA_URL: "kafka:9092"
  KAFKA_TOPIC: "auth-events"

service:
  ports:
    - name: http
      port: 80
      containerPort: 8081

ingress:
  - path: /api/max-service
    port: http
  - path: /api/send-requests
    port: http