apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service1-virtual
spec:
  hosts:
    - local-admin-service # ім'я Service до якого застосовується налаштування
  http:
    - route:
        - destination:
            host: local-admin-service # ім'я Service до якого застосовується налаштування
      timeout: 5s
      retries:
        attempts: 3
        retryOn: connect-failure,refused-stream,5xx
        perTryTimeout: 3s