apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: demo
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
data:
  POSTGRES_USER: "usr"
  POSTGRES_PASSWORD: "pwd"
