apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: titov-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /api/titov-service
            pathType: Prefix
            backend:
              service:
                name: titov-service
                port:
                  number: 80